### ISSUE TITLE
Ability to download and switch between the Zig and Java versions of cubyz

### ISSUE THREAD

**Issue by CardboardDog** [PixelGuys/Cubyz-Launcher#4]
It would be nice if you could run the Zig version from the launcher instead of downloading the source and building it yourself. It looks like the launcher currently downloads the JARs from `https://github.com/PixelGuys/Cubyz/releases/download/[tag]/[file]`, meaning that you would also need to compile and create a release for the zig version at the main Cubyz repository. Maybe the zig versions could be released with a Z instead of a R for Tags. Downloaded binaries could be executed with `Runtime.getRuntime().exec()`. At the top of the launcher there could be a button that switches between the Java and Zig version in case someone wants to use the old Java versions.

**Comment by IntegratedQuantum** [comment]
The plan is to make a new launcher for the zig version, see https://github.com/PixelGuys/Cubyz/issues/227.
The reason why I've gone with the "download source and built it yourself" approach so far is that I don't want to release a new version every week while still allowing the player to experience recent improvements to the game.
The planned launcher would still do this in the background, just in a more user-friendly way.

I don't want to reuse this launcher because it requires installing java and I don't want any user-installed dependencies.
The new launcher also won't allow running the old java releases. The java version won't be updated anymore and I don't want to confuse players with the option to run an older, slower and buggier version of the game. However if for whatever reason people still want to try the old java version, they can do so with the old launcher.
